### PR TITLE
Remove compiler warnings in code generated by nimble_parsec.compile

### PR DESCRIPTION
**Pull request by kipcole9**
Fixes some compiler warnings in generated code.  Some additional remain.  To reproduce:
```
git clone https://github.com/kipcole9/cldr
git checkout nimble_compile
mix deps.get
mix nimble_parsec.compile lib/cldr/language_tag/rfc5646_parser.ex.exs
mix compile
```
Thanks for the collaboration and seasons greetings as well.

### CODE REVIEW

**Comment by josevalim** [comment]
@kipcole9 did you push the nimble_checkout branch to remote?

**Comment by kipcole9** [comment]
Arrgghhhh the branch name is `nimble_compile` (corrected above as well)

**Comment by josevalim** [comment]
Thanks, i removed the warnings for your project but there are likely (many) others since I never didn't paid attention to this particular issue. So please let me know if you find new ones!

**Comment by michalmuskala** [comment]
What if the module were generated using something like:

```elixir
quoted = 
  quote generated: true do
    # definitions...
  end
Module.create(Foo, quoted, __ENV__)
```

I believe this should silence all warnings in general.

**Comment by josevalim** [comment]
@michalmuskala the warnings are emitted when we do source file replacement, in this case, we can't rely on any meta-programming.

**Pull request merged**
