### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by wojtekmach**
Hope it's not too pretentious :)

edit: oh, maybe you were saving this for v0.3 because it's a new feature.

### CODE REVIEW

**Comment by josevalim** [comment]
I’m not super happy with the current approach because we don’t get proper
syntax highlighting.

I’m thinking maybe a better approach would be to have a EXS file and wrap
everything that you want to be replaced between two code comments.

Then when we execute the file we will store what has been generated and we
will inject that between the code comments. The benefit of this approach is
that it’s just a regular file and it would even allow us to do things like
have a file that is compiled naturally and emit a precompiled file from it
too.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by wojtekmach** [comment]
> Then when we execute the file we will store what has been generated and we
will inject that between the code comments.

are you thinking about injecting stuff literally into the same file, thus overwriting the things between comments with the actual code? or like below:

```elixir
defmodule MyParser do
  # defparsec :parse, integer(2)
end
```

```elixir
defmodule MyParser do
  # defparsec :parse, integer(2)
  # below was automatically generated bla bla bla do not edit
  def parse(binary, opts) do
    ...
  end
end
```

the upside is we could continuously edit the `defparsec` call. The downside is we'd lose code highlight for that expression (and it's the most important in that file) because it's a comment.

Or are you thinking about still having 2 files, one source one target? Maybe the source should be in a separate directory that is not `lib/`?

**Comment by wojtekmach** [comment]
or the source is simply lib/my_parser.exs and target is lib/my_parser.ex

**Comment by josevalim** [comment]
> or the source is simply lib/my_parser.exs and target is lib/my_parser.ex

Exactly. The source can also be .ex.exs
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by wojtekmach** [comment]
I see you have response via e-mail so you probably havent see that I amended my previous comment with the following:

edit: actually for lib/my_parser.{ex, exs} we'd get a conflicting module name so we either have just one file or 2 files but in different directories (e.g. in dev the source gets compiled and in prod the target)

**Comment by josevalim** [comment]
@wojtekmach i have pushed to master, let me know what you think. :)

**Pull request closed without merging**
